---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^cmd/xkcdpwd/testdata/.*/stderr\.txt
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
        exclude: ^(\.stentor\.d/|.*/testdata/)

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        exclude: ^(.github/workflows/)

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v6.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.8
    hooks:
      - id: actionlint

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.43.0
    hooks:
      - id: golangci-lint
        args: [--allow-parallel-runners]

ci:
  autofix_prs: false
  autoupdate_commit_msg: "chore: auto-update of pre-commit hooks"
  skip: [actionlint, golangci-lint]
