---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: "^(\
          internal/templates/templates/|\
          cmd/stentor/testdata/.*/stdout|\
          cmd/stentor/testdata/.*/.*\\.tmpl\
          )"
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        exclude: ^(\.stentor\.d/|.*/testdata/)

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        exclude: ^(.github/workflows/)

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.23
    hooks:
      - id: actionlint

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.51.2
    hooks:
      - id: golangci-lint
        args: [--allow-parallel-runners]

ci:
  autofix_prs: false
  autoupdate_commit_msg: "chore: auto-update of pre-commit hooks"
  skip: [actionlint, golangci-lint]
