language: go
sudo: false
notifications:
  email: false
go: 
- 1.12.x
- 1.13.x
- tip
os:
- linux
- osx
env:
- GO111MODULE=on
install:
- go mod download
- go get -v github.com/magefile/mage
script:
- mage -v test
- mage -v coverage
after_success:
- mage -v coveralls
matrix:
  allow_failures:
  - go: tip
  fast_finish: true
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_GO_VERSION =~ ^1\.13
