---
name: Build

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  build:
    name: Build and test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.17, 1.18]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57 # v2.1.4
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Determine cache locations
        id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Check out code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0

      - name: Go Build Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.6
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ matrix.os }}-go-${{ matrix.go_version }}-build-${{ hashFiles('**/go.sum') }}

      - name: Go Module Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.6
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ matrix.os }}-go-${{ matrix.go_version }}-mod-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: go mod download all

      - name: Build
        run: make build

      - name: Test
        run: make test-report

      - name: Send coverage
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2.1.0
        with:
          file: ./reports/coverage.out
          flags: unittests,${{ matrix.os }}
