---
name: Build

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  build:
    name: Build and test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [stable, oldstable]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Test
        run: make test-report

      - name: Send coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./cover.out
          flags: unittests,${{ matrix.os }}
