---
name: Build

on:
  push:
    branches: [main, release-*]
  pull_request:

jobs:
  build:
    name: Build and test on go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [stable, oldstable]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{ matrix.go_version }}
          cache: true
        id: go

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Test
        run: make test-report

      - name: Send coverage
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # v2.1.0
        with:
          file: ./cover.out
          flags: unittests,${{ matrix.os }}
